name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: education/autograding@v1